### ISSUE TITLE
add a search bar

### ISSUE THREAD

**Issue by vtrlx** [VictoriaLacroix/interface#3]
this needs to be actually done with ajax updating. pretty significant but without this we can't even test the rest

@bbeneteau wanna take this?

**Comment by bbeneteau** [comment]
On it

**Comment by vtrlx** [comment]
thank you

**Comment by bbeneteau** [comment]
@VictoriaLacroix having trouble with the syntax of the callback function. I have grabbed the input text from the search box, and am feeding that into the searchOMDBByTitle() function, but stuck with the callback. File: index.html, line 84. I will try again later tonight.

**Comment by vtrlx** [comment]
paste the relevant code snippets?

(surround them in \`\`\`)

**Comment by bbeneteau** [comment]
Getting an error when trying to access the OMDb. 503 (Service Unavailable). OMDb mentions it on their homepage (see attached or visit: https://www.omdbapi.com/).

![err](https://cloud.githubusercontent.com/assets/25368811/22674695/5ba2c116-ecaf-11e6-9d35-59c6e05046e8.png)

**Comment by vtrlx** [comment]
we'll have to wait until the service resumes then.

**Comment by vtrlx** [comment]
closing this. thx for the work
